[build]
base = "."
publish = "dist/"
command = "npm run generate"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = false

[build.processing.css]
bundle = false
minify = true

[build.processing.js]
bundle = false
minify = true

[build.processing.images]
compress = true
